### ISSUE TITLE
sensor never leaves FORCED_MODE

### ISSUE THREAD

**Issue by kimbauters** [pimoroni/bme680#9]
I've been looking through the code in detail, and there seems to be something odd with `get_sensor_data(self)`. The power mode is set to `FORCED_MODE` at the start, but is never returned to the mode it was in when starting the method. Is this intentional? Or should the mode be saved when entering this method, and reset just before returning?

**Comment by Gadgetoid** [comment]
`FORCED_MODE` should trigger a single measurement and then reset to 0.

The data sheet says:

* Single TPHG cycle is performed
* Sensor automatically returns to sleep mode afterwards
* Gas sensor heater only operates during gas measurement
